/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.gradle.tools.trace.app

import com.google.gson.Gson
import java.io.File

fun main(args: Array<String>) {
    val traceFile = File(args[0])
    val records = Gson().fromJson(traceFile.readText(), Array<BuildOperationRecord>::class.java)
    println("Read ${records.size} records from ${traceFile.name}")
    val traceEvents = TraceConverter().convert(records.toList())
    val traceFileJson = File(traceFile.parentFile, traceFile.nameWithoutExtension + "-chrome.json")
    traceFileJson.writeText(Gson().toJson(traceEvents))
    println("Wrote ${traceEvents.size} events to ${traceFileJson.absolutePath}")
}
