/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("gradlebuild.tools.trace.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("com.google.code.gson:gson:2.10")
}
repositories {
    mavenCentral()
}

application {
    // Define the main class for the application.
    mainClass.set("org.gradle.tools.trace.app.AppKt")
}
