/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("gradlebuild.tools.trace.kotlin-application-conventions")
    id("com.google.protobuf") version ("0.9.1")
}

dependencies {
    api("com.google.protobuf:protobuf-java:3.21.12")
    implementation("org.apache.commons:commons-text")
    implementation("com.google.code.gson:gson:2.10")
}
repositories {
    mavenCentral()
}

application {
    // Define the main class for the application.
    mainClass.set("org.gradle.tools.trace.app.AppKt")
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.21.12"
    }
}
